전 코드리뷰 피드백 수정.
hackersground-kr/operations pull request #32
Opened 2023-06-03 06:10 UTC by isp829

아침에 주셨던 코드리뷰에 있었던 부분들을 수정하고 추가하였습니다.

2023-06-03 06:24 UTC, justinyoo requested changes
리뷰 코멘트 추가했습니다.

덧: 기존 PR을 닫고 새 PR을 여는 대신, 기존 PR을 계속 수정해 주세요. 지금 쓰기 권한을 드렸다고 맘대로 PR 머지하시면 PR과 코드리뷰의 컨텍스트와 히스토리가 다 깨져요.

2023-06-03 06:24 UTC, justinyoo commented on .github/workflows/csc-challenge-verified.yaml
> +        url: 'https://prod-01.koreacentral.logic.azure.com:443/workflows/eb085e233f4146d6a9368c5db4121154/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=
* 이 URL 값은 언제든 바뀔 수 있습니다
* invoke? 뒷부분의 값은 SAS 토큰이라고 민감하게 다뤄야 하는 값이므로 여기에 이렇게 노출시키면 안됩니다.

2023-06-03 07:17 UTC, isp829 commented on .github/workflows/csc-challenge-verified.yaml
> +        url: 'https://prod-01.koreacentral.logic.azure.com:443/workflows/eb085e233f4146d6a9368c5db4121154/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=
넵 깃허브 secrets로 바꿔놓겠습니다.

2023-06-03 08:10 UTC, isp829 commented
브랜치에서 추가 수정하고 올렸습니다.

2023-06-03 08:37 UTC, justinyoo requested changes
오타가 있는 것 같으니 확인해 보시고 수정해 주세욥.

2023-06-03 08:37 UTC, justinyoo commented on .github/workflows/csc-challenge-verified.yaml
> +        url: ${{ secrets.DISCORD_WEBHOOK_URL }}
여기가... 디스코드 URL이 아닌 듯 합니다...?

2023-06-03 08:39 UTC, isp829 commented on .github/workflows/csc-challenge-verified.yaml
> +        url: ${{ secrets.DISCORD_WEBHOOK_URL }}
네 디스코드에서 제공하는 webhook의 url을 따로 지정해줘야 합니다.

2023-06-03 08:50 UTC, justinyoo commented on .github/workflows/csc-challenge-verified.yaml
> +        url: ${{ secrets.DISCORD_WEBHOOK_URL }}
여긴 파워 오토메이트 액션인데도 디스코드 URL을 쓴다구요?

2023-06-03 08:58 UTC, isp829 commented on .github/workflows/csc-challenge-verified.yaml
> +        url: ${{ secrets.DISCORD_WEBHOOK_URL }}
아 복사 붙여넣기하는 과정에서 잘못 붙여넣었나봅니다. 수정하겠습니다.

2023-06-03 09:13 UTC, justinyoo requested changes
23-26 번 쪽에 제목에 `]` 없을 경우 에러가 생기더라구요. 아래처럼 바꿔주시면 됩니다.

```powershell
        $code = $title.Contains("]") ? $title.Substring(0, $title.IndexOf(']')).Replace("[", "").Replace("]", "").Trim().ToLowerInvariant() : ""
        $codeUpper = ($code -ne "") ? $code.ToUpperInvariant() : ""
        $codes = @("az-900", "ai-900", "dp-900", "pl-900", "sc-900", "ms-900")
        $isValidCode = ($code -ne "") ? $($codes.Contains($code)).ToString().ToLowerInvariant() : $false
```

2023-06-05 00:09 UTC, justinyoo approved these changes
수고하셨습니다! 좀 더 가독성을 높이는 방법은 차차 고민해 보시지욥!

2023-06-05 00:09 UTC, merged