Microsoft Learn 챌린지 완료 여부 확인 스크립트
hackersground-kr/operations pull request #82
Opened 2023-06-11 05:17 UTC by chadata

**사용설명서: Microsoft Learn 챌린지 완료 여부 확인 스크립트**

이 사용설명서는 Python Selenium을 사용하여 Microsoft Learn 프로필에서 특정 챌린지의 완료 여부를 확인하는 스크립트에 대한 설명을 제공합니다.

**1. 필수 요구사항**
- Python 3.x 버전 이상
- Selenium 패키지 설치
- Chrome 브라우저
- ChromeDriver 설치 (https://chromedriver.chromium.org/downloads 에서 Chrome 버전에 맞는 드라이버 다운로드)

**2. 스크립트 설치 및 설정**
- Python 환경에서 위의 코드를 사용하려는 디렉토리에 저장합니다.
- `webdriver_service` 변수에서 ChromeDriver 경로를 올바른 경로로 수정합니다. (예: `webdriver_service = Service('./chromedriver_mac64/chromedriver.exe')`)
- 필요에 따라 다른 옵션을 설정할 수 있습니다. (예: `options.add_argument('--headless')`는 브라우저를 표시하지 않고 실행하는 옵션입니다.)

**3. 스크립트 실행**
- 터미널 또는 명령 프롬프트에서 스크립트를 실행합니다.
- 실행 중에는 Microsoft Learn 프로필의 링크를 입력하라는 메시지가 표시됩니다. Microsoft Learn 프로필 페이지의 URL을 입력합니다.
- 다음으로, 완료 여부를 확인하려는 챌린지 코드를 입력하라는 메시지가 표시됩니다. 확인하려는 챌린지의 코드를 입력합니다. (예: `AZ-900`)
- 스크립트는 입력한 프로필에서 해당 챌린지의 필수 배지가 있는지 확인하고 결과를 표시합니다.

**4. 결과 해석**
- 스크립트는 해당 챌린지의 필수 배지가 모두 있는 경우 "완료 /ok"를 출력합니다.
- 필수 배지 중 하나라도 없는 경우 "NO"를 출력합니다.

**5. 스크립트 종료**
- 스크립트 실행이 완료되면 브라우저가 종료됩니다.

**참고 사항**
- 스크립트는 Microsoft Learn 프로필의 배지 제목이 코드에 기재된 것과 동일하다고 가정합니다. Microsoft Learn 플랫폼에서 배지 제목이 변경된 경우 코드를 업데이트해야 합니다.
- 스크립트의 실행 결과는 콘솔에 표시됩니다. 필요에 따라 코드를 수정하여 결과를 파일에 저장하거나 다른 방식으로 처리할 수 있습니다.

2023-06-11 08:10 UTC, justinyoo requested changes
@chadata 감사합니다! 이제 코드리뷰를 한 번 시작해 볼까요? 조금 길어질 수 있습니다.

- 셀레니움 보다는 좀 더 최신의 [Playwright 패키지](https://playwright.dev/python/docs/intro)를 사용해서 다시 작성해 보세요.
- 리포지토리의 루트가 아닌 `check-csc-trophies` 디렉토리 안에 파일을 넣어 주세요.
- 해당 디렉토리 안에 `README.md` 파일도 추가해서 이슈 본문에 있는 내용을 그대로 넣어주세요.

우선 지금은 여기까지 해 보겠습니다. 시간 날 때 한 번 보완해 주시면 좋겠습니다.

2023-06-11 12:41 UTC, chadata commented
알겠습니다! Playwright를 사용하여 코드를 작성하고, check-csc-trophies 디렉토리에 파일을 배치하겠습니다. README.md 파일도 작성하여 이슈 본문에 있는 내용을 그대로 포함하도록 하겠습니다.

새로운 코드와 README.md 파일을 작성하고 이슈에 업데이트하겠습니다. 작업이 완료되면 다시 연락드리도록 하겠습니다. 조금만 기다려주시기 바랍니다.

2023-06-12 00:12 UTC, justinyoo requested changes
오우 상당히 좋아졌습니다! 몇가지 코멘트를 좀 더 달아봤어요. 확인해 보시겠습니까?

2023-06-12 00:12 UTC, justinyoo commented on check-csc-trophies/README.md
> +   ```
혹시 이 부분 requirements.txt 파일을 이용하면 어떤가요?

2023-06-12 00:12 UTC, justinyoo commented on check-csc-trophies/README.md
> +  - playwright-sync==1.11.1
앞서 언급한 requirements.txt 파일을 이용하면 이 부분을 쉽게 해결할 수 있을 것 같습니다.

2023-06-12 00:12 UTC, justinyoo commented on check-csc-trophies/README.md
> +- Python 3.x
3.x 버전이면 파이썬 3 버전이면 아무거나 다 되는 건가요, 아니면 그래도 3.8 이상이라든가 하는 식으로 구체화 시켜주는 것이 좋은가요?

2023-06-12 00:12 UTC, justinyoo commented on check-csc-trophies/README.md
> +1. 이 저장소를 클론하거나 `check-csc-trophies.py` 파일을 다운로드합니다.
혹시 이 전에 `virtualenv` 같은 사전 작업이 필요하지 않은지 확인해 주시겠어요?

2023-06-12 00:12 UTC, justinyoo commented on check-csc-trophies/README.md
> +   - `MS-900`: Microsoft 365 기초 챌린지
여기서 아규먼트를 프롬프트로 입력 받는 방법도 좋은데, 그냥 `python check-csc-trophies.py -code "AZ-900"` 같은 식으로도 할 수 있는 방법이 있을까요? 그렇게 하면 CI/CD 파이프라인 안에서도 적용할 수 있을 것 같기도 합니다.

2023-06-12 00:12 UTC, justinyoo commented on check-csc-trophies/check-csc-trophies.py
> +            Flag_ms_900 = 0
여기가 동일한 코드가 계속 반복되는 것처럼 보이는데, DRY(Don't Repeat Yourself) 기법에 의거해서 리팩토링이 가능할까요?

2023-06-12 00:12 UTC, justinyoo commented on check-csc-trophies/check-csc-trophies.py
> +                print("MS-900 NO")
여기도 마찬가지로 펑션 하나로 빼서 리팩토링이 가능해 보입니다.

2023-06-12 00:12 UTC, justinyoo commented on check-csc-trophies/check-csc-trophies.py
> +challenge_code = input("\n완료를 확인하고 싶은 챌린지 코드를 입력해 주세요 (예시: AZ-900): ")
이 부분도 상당히 좋은데, 이건 이것대로 냅두고 앞서 언급했던것처럼 `--code "AZ-900"` 같은 식으로 파라미터/아규먼트를 통해서도 처리할 수 있게 하면 어떨까요?

2023-06-12 07:42 UTC, chadata commented
지금 까지의 모든 Changes requested를 반영하여 commit 했습니다. 감사합니다.

2023-06-12 08:09 UTC, chadata commented
지금 까지의 모든 Changes requested를 반영하여 commit 했습니다. 감사합니다.
다른 수정사항이 있으면 또 말씀해 주세요. 빠른 시일내에 개선하겠습니다.

2023-06-14 04:34 UTC, justinyoo approved these changes
고생하셨습니다! 우선 머지해 놓고, 돌려보다가 이슈가 생기면 다시 여쭤볼께욥

2023-06-14 04:35 UTC, merged